namespace: helm-namespace
buildId: 8 # will be incremented in the CI/CD
web:
  image:
    dockerHubId: sauravsrivastav
    name: sauravsrivastav/web
    tag: v1 # #{Build.BuildId}#
    replicaCount: 5
  port: 80
sql:
  image:
    dockerHubId: microsoft
    name: mssql-server-linux
    tag: latest
    replicaCount: 1
  port: 1433

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
