apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: paascoe
data:
  db-connection-string: Server=mssql-service-helm;Database=EmployeesDB;User=SA;Password=@Aa123456;
