kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-1gb-{{ .Values.buildId }} # each PVC should reference only one StorageClass
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi