apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: paascoe-deployment-helm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: paascoe
  replicas: {{ .Values.web.image.replicaCount }}
  template:
    metadata:
      labels:
        app: paascoe
    spec:
      containers:
      - name: paascoe
        image: {{ .Values.web.image.dockerHubId }}/{{ .Values.web.image.name }}:{{ .Values.web.image.tag }}
        ports:
        - containerPort: {{ .Values.web.port }}
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
        env:
          - name: ConnectionStrings__EmployeesContext
            valueFrom:
#              secretKeyRef:
#                name: mssql-secret
#                key: db-connection-string-secret
              configMapKeyRef:
                name: mssql-connection-configmap
                key: db-connection-string
---
kind: Service
apiVersion: v1
metadata:
  name: paascoe-service-helm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: paascoe
  ports:
  - protocol: TCP
    port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
  type: LoadBalancer